[package]
name = "pais-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "pais_rs"
crate-type = ["cdylib"]

[dependencies]
pyo3 = "0.18.1"
rootfind = "0.7.0"
